name: news pipeline

on:
  schedule:
    - cron: '0 4 * * 1-5'     # UTC 04:00 = 한국 13:00 평일
  workflow_dispatch: {}       # 수동 실행 가능

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create work directory
        run: mkdir -p work

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline script
        run: python scripts/run_pipeline.py
        
      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: pipeline-results
          path: work/
